### ISSUE TITLE
没有个文档吗

### ISSUE THREAD

**Issue by ABetterCat** [why444216978/gin-api#1]
分布式锁在哪里

**Comment by why444216978** [comment]
感谢支持，很抱歉，有不少人反馈需要文档，目前工作比较忙，还有很多待完善的地方，优先级都要高于文档，后续一定会慢慢把文档补全。

**Comment by why444216978** [comment]
分布式锁，目前只支持了 redis：https://github.com/why444216978/gin-api/tree/master/library/lock

**Comment by ABetterCat** [comment]
好的，感谢回复，期待完善，学习啦
